task_name: pick_toy


# abs_pose_limit_low: [0.5845,  -0.20959,  0.40307, -3.14156, -0.14725, -0.1215 ]
# abs_pose_limit_high: [0.6673,  -0.00643,  0.56593,   3.1415,   0.31587,  0.23937]
# abs_pose_limit_low: [ 0.61617, -0.13091,  0.39379, -3.14145, -0.11459, -0.06785]
# abs_pose_limit_high: [ 0.6779, -0.01115,  0.49653,  3.14153,  0.18388,  0.15519]

abs_pose_limit_low: [ 0.55566, -0.1294, 0.16493, -3.1369, -0.10172, -0.12185]
abs_pose_limit_high:  [0.71103, 0.07275, 0.37902, 3.14012, 0.22937, 0.18198]


# reset_joint: [-0.430447 , 0.516946 , 0.525393 , -1.229498 , -0.246238 , 1.685771 , 0.152009]
# reset_joint: [ 0.0391 ,  0.35801, -0.05436, -1.6409,   0.04237,  1.87316, -0.04928]
reset_joint: [-0.03677227,  0.3262354,   0.02097587, -1.8432305,  -0.00676017,  2.1204965, -0.07338729]

"dataset": {
    # "repo_id": "lerobot/RoboMIND",
    "repo_id": silri,
    "use_imagenet_stats": false,
    # "root": "/home/eai/Dev/hermine/HIL-RL-Project/HIL-RL/experiments/pick_toy/offline_dataset",
    # "root": "/media/HIL-RL-Project/HIL-RL/experiments/pick_toy/offline_dataset",
    # todo: this dataset is only for debugging
    "root": "/media/HIL-RL-Project/HIL-RL/experiments/pick_toy/offline_dataset",
    # "root": "/home/eai/Dev/linda/HIL-RL-Project/lerobot_data_0914/franka01_Plug_into_socket" 
}

gripper_penalty: -0.2
# intervene_penalty: -0.2
classifier_cfg:
    classifier_keys: ["right"]
    pretrained_encoder_path: ../resnet10_params.pkl
    checkpoint_path: classifier/checkpoints/000500
    dataset_path: offline_dataset/insert_usb_franka_1028
    reward_pos: 10.0
    reward_neg: -0.05
    require_train: true 
    task_name: ${task_name}
    algorithm: hil-serl
    target_hz: 10
    batch_size: 128
    enable_stacking: false
    load_classifier: ${load_classifier}

close_gripper: false
fix_gripper: false
enable_rotation: true
max_episode_length: 120
max_train_time: 2400

resume_model: false
resume_path: None
load_path: null

task_description: "pick up the gray plush toy on pink plate and lift it"
t5_text_embeddings_path: "/media/hermine_dataset/franka1/franka1_h5data_convert_cosmos/pick_toy/demo_data/t5_embeddings.pkl"
dataset_stats_path: "/media/hermine_dataset/franka1/franka1_h5data_convert_cosmos/pick_toy/demo_data/dataset_statistics.json"

# task_description: "pick up the gray plush toy on pink plate and lift it"
# t5_text_embeddings_path: "/home/eai/Dev/hermine/HIL-RL-Project/dataset/pick_toy/demo_data/t5_embeddings.pkl"
# dataset_stats_path: "/home/eai/Dev/hermine/HIL-RL-Project/dataset/pick_toy/demo_data/dataset_statistics.json"